---
ansible_connection: winrm
ansible_user: Administrator
ansible_password: "{{ redis }}"
ansible_winrm_server_cert_validation: ignore
ansible_winrm_trasport: basic
ansible_port: 5986 #5985 (HTTP)
ansible_winrm_server_cert_validation: ignore
zabbix_agent_server: zabbixserver
zabbix_url: http://zabbixserver
zabbix_api_use: true
zabbix_api_user: Admin
zabbix_api_pass: StrongPa$$w0rd
zabbix_interface_port: "10050"
zabbix_host_groups: ["Windows servers"]
zabbix_link_templates: ["Windows by Zabbix agent"]
zabbix_interface_type: agent
zabbix_interface_use_ip: "0"
zabbix_interface_ip: ""
zabbix_host_description: "My windows server"
zabbix_host_status: enabled
