version: '3'

services:
  zmysql:
    image: mysql:5.7
    container_name: zabbix-mysql
    ports:
      - '3306:3306'
    volumes:
      - /opt/apps/docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="password"
  zserver:
    image: zabbix/zabbix-server-mysql
    container_name: zserver
    ports:
      - '10051:10051'
    volumes:
      - /opt/apps/docker/mysql/data:/var/lib/mysql
    environment:
      - DB_SERVER_HOST=zmysql
      - MYSQL_USER="root"
      - MYSQL_ROOT_PASSWORD="password"
  zadmin:
    image: zabbix/zabbix-web-apache-mysql
    container_name: zadmin
    ports:
      - '80:8080'
    volumes:
      - /opt/apps/docker/mysql/data:/var/lib/mysql
    environment:
      - DB_SERVER_HOST=zmysql
      - MYSQL_USER="root"
      - MYSQL_ROOT_PASSWORD="password"
      - PHP_TZ="America/Chicago"
      - ZBX_SERVER_HOST=zserver
